### ISSUE TITLE
Deep Fuzzing on Newly Modified Solidity Files

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#515]
Random thought I had but since I [wrote that action](https://github.com/ubiquity/bounty-bot/blob/c1c6c99336f34ac5e94efaed49c9f218fb7a2d76/.github/workflows/push.yml#L36-L43) that will: 

1. read the bounty-bot repo and 
3. build if any source code changes occur, and then 
4. commit the built file to the repo 

It inspired me to think of what other compute we can delegate to the cloud to make the dev experience better. 

What if we do something similar with deep fuzzing, but only on modified Solidity files? I understand that deep fuzzing takes a lot of time, so we could run it for the entire codebase one time, and then only run it on modified Solidity files moving forward? I vaguely recall a discussion related to how deep fuzzing is super slow.

transmissions11 has a Foundry template that does a deep fuzz on everything when merged to main, which served as another point of inspiration for me.

```yml
      - name: Run tests
        run: forge test
        env:
          # Only fuzz intensely if we're running this action on a push to main or for a PR going into main:
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'intense' }}
```
https://github.com/transmissions11/foundry-template/blob/0bf8e53589f2e8f72e41baf672c25aa35ba57295/.github/workflows/tests.yml#L28-L32
